version: "2"

networks:
     test:

services:
     besu:
          image: hyperledger/besu:${IMAGE_TAG}
          environment:
               - BESU_RPC_HTTP_ENABLED=true
               - BESU_RPC_HTTP_PORT=${JSON_RPC_PORT}
          ports:
               - "8545:8545"
          container_name: besu
          networks:
               - test
